export const types = {
  MOVIE_LOADING: "MOVIE_LOADING",

  LOAD_MOVIES: "LOAD_MOVIES",
  LOAD_MOVIES_SUCCESS: "LOAD_MOVIES_SUCCESS",
  LOAD_MOVIES_ERROR: "LOAD_MOVIES_ERROR",

  LOAD_MOVIE: "LOAD_MOVIE",
  LOAD_MOVIE_SUCCESS: "LOAD_MOVIE_SUCCESS",
  LOAD_MOVIE_ERROR: "LOAD_MOVIE_ERROR",

  SEARCH_MOVIES: "SEARCH_MOVIES",

  BOOKING_LOADING: "BOOKING_LOADING",

  STORE_BOOKING: "STORE_BOOKING",
  STORE_BOOKING_SUCCESS: "STORE_BOOKING_SUCCESS",
  STORE_BOOKING_ERROR: "STORE_BOOKING_ERROR",

  LOAD_BOOKING: "LOAD_BOOKING",
  LOAD_BOOKING_SUCCESS: "LOAD_BOOKING_SUCCESS",
  LOAD_BOOKING_ERROR: "LOAD_BOOKING_ERROR",
};
